### ISSUE TITLE
Found a kind of odd conflict with Artifacts

### ISSUE THREAD

**Issue by githubbingitup** [CleverNucleus/PlayerEx#10]
Obviously not every mod is going to work with each other so I don't mean to be annoying by reporting another.
However, this mod doesn't seem to do anything similar to yours so I found the conflict strange and thought I should post it.

The mod Artifacts adds some Trinket accessories: https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric

Running it alongside PlayerEx causes world generation to become unresponsive and crash the game. The only mods being used are Artifacts (and Trinkets, as its a dependency) as well as PlayerEx and FabricAPI. I've attached a crash log from regular MC and Not Enough Crashes.

[regularcrash.txt](https://github.com/CleverNucleus/PlayerEx/files/6719064/regularcrash.txt)
[notenoughcrashes.txt](https://github.com/CleverNucleus/PlayerEx/files/6719065/notenoughcrashes.txt)

Let me know if you think I should post this on the Artifacts github.

**Comment by CleverNucleus** [comment]
Hi there,
Yeah this is a weird one; there's nothing in either of these mods that effects world gen. Thanks for sending the logs, I'll look into it asap.

**Comment by CleverNucleus** [comment]
Fixed with v2.0.2 (although some weird interactions remain with, for example, steadfast slippers - that give 100% knockback resistance - no more crashes though, hopefully).
