### ISSUE TITLE
Entities that drop or give experience orbs or just experience sometimes dont give or drop

### ISSUE THREAD

**Issue by nixord** [CleverNucleus/PlayerEx#100]
The title says it but basically whenever I kill a mob, use a bottle of experience or anything that would give me xp in some way it just doesnt for some reason. Does it say anywhere in the mod that it reworks the experience drop table or something?

Minecraft version: 1.19.2
Modpack: FO (Fabulously Optimized) with mods added by myself

PD: Yes, I made sure to check the other mods I added to it and only PlayerEx has this issue when I add it

**Comment by CleverNucleus** [comment]
Hi there,
This is intentional - PlayerEx recently implemented a chunk-based experience system. Most of the time it should not affect gameplay too noticeably, it's main role is to nerf experience gain from mob farms.

You can read more about it [here](https://clevernucleus.github.io/playerex-1.18.2_faq.html#6-how-does-the-chunk-based-experience-system-work).

For those who don't like this, PlayerEx includes configuration options to a) modify the chunk-based experience system and b) the ability to disable it altogether. Please see [here](https://clevernucleus.github.io/playerex-1.18.2_content.html#config) for configuration information - specifically, setting `XP Negation Factor` to `100` disables the system.

Hope that helps,
Thanks.

**Comment by nixord** [comment]
> Hi there, This is intentional - PlayerEx recently implemented a chunk-based experience system. Most of the time it should not affect gameplay too noticeably, its main role is to nerf experience gain from mob farms.
> 
> You can read more about it [here](https://clevernucleus.github.io/playerex-1.18.2_faq.html#6-how-does-the-chunk-based-experience-system-work).
> 
> For those who don't like this, PlayerEx includes configuration options to a) modify the chunk-based experience system or b) disable it altogether. Please see [here](https://clevernucleus.github.io/playerex-1.18.2_content.html#config) for configuration information - specifically, setting `XP Negation Factor` to `100` disables the system.
> 
> Hope that helps, Thanks.

Thank you so much Nucleus! So I was right! You forsaw ppl would build mob farms to abuse these things! Im sorry for being dumb and hopefully I wont do this again <3

**Comment by CleverNucleus** [comment]
No worries; I didn't think it was a dumb question 👍

**Comment by GulliUlli** [comment]
hi i have the same issue in my mobfarm, i dont get any exp. i set the factors in config to 100 but nothing changed. no exp for me^^

**Comment by CleverNucleus** [comment]
Ensure that you have restarted the game (and if it is a server, the server must be restarted too).

**Comment by GulliUlli** [comment]
yes i know^^ but nothing worked. i tested 100 100 100 , 1 50000 50000, 1 1 50000, 1 50000 1, nothing worked to get exp in that chunk again.

**Comment by CleverNucleus** [comment]
@GulliUlli 
How are you testing this? I should note that changing the config will not immediately result in experience being dropped regularly in that chunk. The chunk will still take some time to 'recharge' before experience can be produced again. What I'm trying to get at here is that if you are changing the config, restarting the game, logging into the world and immediately dropping xp pots to see if the xp drops - it won't. You need to wait. You can reduce this waiting time by increasing the 'Restorative Force' value in the config.

As I have verified that this system works, all I can really do is suggest the aforementioned - and if even after waiting xp is still not being created, perhaps try deleting the config and editing it manually.

**Comment by GulliUlli** [comment]
@CleverNucleus 
so i changed in config:
"restorativeForceTicks": 
 "restorativeForceMultiplier":
"expNegationFactor":
to the values i wrote abrove. then i started my server, joined the game killt mobs in my mobfarm and didnt get exp. then i wait 5min befor the farm and then i killed again. no exp. then i changed in configs to the next kombination. etc. nothing worked. its only one chunk. 

would it be possible to add an command for chunk reset?

**Comment by CleverNucleus** [comment]
So with the numbers you have written the chunk will not reset. However, I have also uncovered what _could_ be considered a bug, but isn't quite. When setting the `expNegationFactor` to 100, it indeed reverts the experience system to vanilla, but currently that also means that the chunk will also not regenerate its ability to produce experience.

Try the following:

1. Set your config to 

```json
"restorativeForceTicks": 1,
"restorativeForceMultiplier": 10000,
"expNegationFactor": 95,
```

2. Load up your world and leave it running for 10 minutes (without killing mobs).
3. Close your world, and set the config to 

```json
"restorativeForceTicks": 1,
"restorativeForceMultiplier": 10000,
"expNegationFactor": 100,
```
4. Load your world up, it should now be back to normal.

Apologies for that - it's not quite a bug, but it is a bit of an oversight. Thanks.

**Comment by GulliUlli** [comment]
so i tryed exactly how you said, but this one chunk will not work... i dont understand that. i looked in all configs, if another mod maybe is donig that, but i didnt found any config, where i would say, ok maybe there... :/

but nice, if you found another issue :D
