### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$$0" is null

### ISSUE THREAD

**Issue by NamelessAshes** [CleverNucleus/PlayerEx#101]
Hello, there's some java null pointer error occurred in my minecraft server. If I remove this mod, it will not crash again. here's some error message:

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$$0" is null
	at net.minecraft.class_2519.method_23256(class_2519.java:71)
	at net.minecraft.class_2487.method_10582(class_2487.java:231)
	at com.github.clevernucleus.opc.impl.PlayerCacheImpl.toNbt(PlayerCacheImpl.java:150)
	at net.minecraft.class_31.handler$ckf000$onUpdateProperties(class_31.java:697)
	at net.minecraft.class_31.method_158(class_31.java)
	at net.minecraft.class_31.method_163(class_31.java:231)
	at net.minecraft.class_32$class_5143.method_27426(class_32.java:340)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:568)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:585)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:848)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:---- Minecraft Crash Report ----
// My bad.

Time: 1/13/23, 3:42 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$$0" is null
	at net.minecraft.class_2519.method_23256(class_2519.java:71)
	at net.minecraft.class_2487.method_10582(class_2487.java:231)
	at com.github.clevernucleus.opc.impl.PlayerCacheImpl.toNbt(PlayerCacheImpl.java:150)
	at net.minecraft.class_31.handler$ckf000$onUpdateProperties(class_31.java:697)
	at net.minecraft.class_31.method_158(class_31.java)
	at net.minecraft.class_31.method_163(class_31.java:231)
	at net.minecraft.class_32$class_5143.method_27426(class_32.java:340)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:568)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:585)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:848)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows Server 2022 (amd64) version 10.0
	Java Version: 17.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1060041240 bytes (1010 MiB) / 5989466112 bytes (5712 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7542 32-Core Processor                
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 2.89
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Microsoft Hyper-V 视频
	Graphics card #0 vendor: Microsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=10.0.20348.1
	Graphics card #1 name: Microsoft Remote Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=10.0.20348.1
	Memory slot #0 capacity (MB): 3968.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 4224.00
	Memory slot #1 clockSpeed (GHz): 0.00
	Memory slot #1 type: Other
	Virtual memory max (MB): 12489.54
	Virtual memory used (MB): 8888.63
	Swap memory total (MB): 4297.99
	Swap memory used (MB): 969.45
	JVM Flags: 2 total; -Xms2G -Xmx7G
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.4.9
		alloy_forgery: Alloy Forgery 2.0.9+1.18
		amethystequipment: Amethyst Equipment 1.18.1
		anvil_fix: AnvilFix development+custom-1.18
		appleskin: AppleSkin 2.3.0+mc1.18.1
		arcanus: Arcanus 1.27
		architectury: Architectury 3.9.55
		awesomedungeon: Awesome Dungeon 2.0.8
		awesomedungeonend: Awesome Dungeon Edition end 1.0.0
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.1
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.6
		balm-fabric: Balm 2.4.3+0
		basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
		bclib: BCLib 1.3.5
		betterend: Better End 1.0.3
		betternether: Better Nether 6.0.12
		betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
		boneequipment: Bone Equipment 1.18.1
		bookshelf: Bookshelf 12.0.23
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.5-1.18
		botania: Botania 1.18.1-429-FABRIC
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.1
		cavetweaks: Cave Tweaks 1.0
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.62
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.9
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		companion: Companion 1.2.1
		copperequipment: Copper Equipment fabric-1.18.1-v2.0.0
		crafttweaker: CraftTweaker 9.0.81
		crawl: Crawl 0.10.2
		creeperoverhaul: Creeper Overhaul 0.3.0
		crosshairmod: Crosshair Mod 0.4.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portal Api 0.0.1-beta49-1.18
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		dataattributes: Data Attributes 1.1.5
		defaultoptions: Default Options 14.1.0
		dehydration: Dehydration 1.2.7
		doublejump: Double Jump Mod 1.0.1+mc1.18
		dragonloot: DragonLoot 1.0.10
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49d-fabric
		dusk: Dusk Mod 1.18.2-1.9
		ec-core: Essential Commands Core 1.0.1-mc1.18.1
		edenring: EdenRing 0.3.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		emeraldequipment: Emerald Equipment 1.18.1
		enchantment_force: enchantment_force 0.1.7
		enhancedcelestials: Enhanced Celestials 2.0.6
		environmentz: EnvironmentZ 1.2.1
		essential_commands: Essential Commands 0.24.5-mc1.18.1
		experiencebugfix: Experience Bug Fix 18
		extended_armor_bars: Extended Armor Bars 1.1.0
		extraalchemy: Extra Alchemy 1.7.0
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-furnaces: Fabric Furnaces 2.1.0-1.18.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricenchantments: Fabric Enchantments 0.7.1
		fabricloader: Fabric Loader 0.13.3
		fabricshieldlib: Fabric Shield Lib 1.5.0-1.18
		farsighted-mobs: Farsighted Mobs 1.1-1.18
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		ferritecore: FerriteCore 4.1.2
		fiber: fiber 0.23.0-2
		flintytools: Flinty Tools 1.1.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		gateofbabylon: Gate Of Babylon 1.6.0-1.18.1
		geckolib3: Geckolib 3.0.33
		gobber2: Gobber2 2.5.63.3
		graveyard: The Graveyard 1.6
		greater_eye: Greater Eye of Ender 1.3.21
		gud_recipe_confidence: Recipe Confidence 1.0.2
		heartytrinkets: Hearty Trinkets 1.18.1-1.0.0
		hookshot: Hookshot 24.0
		hoverpets: Hover Pets 0.2.0
		iceberg: Iceberg 1.0.38
		impaled: Impaled 1.0.3
		imperishableitems: Imperishable Items 2.1.2
		incantationem: Incantationem 1.1.3+1.18.1
		incubus_core: Incubus Core 1.6.6+1.18.1
		infusion_table: Infusion Table 1.0.5
		ingredient-extension-api: Ingredient Extension API 2.0.1
		inmis: Inmis 2.5.1-1.18.1
		interactic: Interactic 0.1.8+1.18
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		kjsextras: KubeJS Extras 1.5.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
		kubejs: KubeJS 1801.4.3-build.310
		lazydfu: LazyDFU 0.1.2
		libraryferret: Library Ferret 1.0.3
		lychee: Lychee Tweaker 1.5.1
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magiccombatwands: Magic Combat Wands 1.0.1
		magna: Magna 1.7.0-1.18-pre1
		mcda: MC Dungeons Armors 2.0.6
		mcdar: MC Dungeons Artifacts 1.4.8
		mcdw: MC Dungeons Weapons 4.3.2
		megaparrot: Megaparrot 1.0.3
		mesh: Mesh 0.19.0-alpha
		mesh_api: Mesh API 0.19.0-alpha
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mobz: MobZ 3.3.1
		morebannerfeatures: More Banner Features 1.1.3
		moretags: More Tags 2.0.2
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.1+1.18.1
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		mythicmetals: Mythic Metals 0.12.2
		mythicmounts: Mythic Mounts 1.18.1-7.0
		net_objecthunter_exp4j: exp4j 0.4.8
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		numismatic-overhaul: Numismatic Overhaul 0.1.8+1.18
		nyfsquiver: Nyf's Quivers Fabric-0.4.0-1.18
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.1-1.18.1
		opc: Offline Player Cache 0.0.1
		openloader: OpenLoader 11.0.4
		org_javassist_javassist: javassist 3.28.0-GA
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_reflections_reflections: reflections 0.10.2
		oro_config: OroArmor Config 2.1.0
		owo: oωo 0.5.2+1.18
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.3.0+1.14.4-1.19
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		playerex: PlayerEx 3.1.4
		polymorph: Polymorph 0.0.20-1.18.2
		pugh_lib: Pugh Lib 1.2.15
		pugh_tools: Pugh Tools 1.1.22
		puzzleslib: Puzzles Lib 3.2.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reinfbarrel: Reinforced Barrels 2.0.0+1.18
		reinfchest: Reinforced Chests 2.0.0+1.18
		reinfcore: Reinforced Core 2.0.0+1.18
		reinfshulker: Reinforced Shulker Boxes 2.0.0+1.18
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		reroll: Reroll 1.4.0-1.18.1
		rhino: Rhino 1801.1.9-build.135
		ringsofascension: Rings of Ascension 1.0
		roughlyenoughitems: Roughly Enough Items 7.4.456
		roughlyenoughresources: Roughly Enough Resources 2.4.1
		runelic: Runelic 10.0.6
		sculk_worm: Sculk Worm 0.1.5
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		smoothboot: Smooth Boot 1.18-1.7.0
		stacc: Stacc 1.3.0
		starlight: Starlight 1.0.0+fabric.d0a3220
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.2
		tellme: TellMe 0.9.0
		the_aether: Paradise Lost 1.6.9+1.18.1
		things: Things 0.2.15+1.18
		tinyskeletons: Tiny Skeletons 3.1.0
		toolstats: ToolStats 8.0.6
		torchbowmod: TorchBowMod 1.0
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.2.0
		tradingpost: Trading Post 3.1.2
		trashslot: TrashSlot 11.0.2
		travelersbackpack: Traveler's Backpack 1.18.1-7.0.0
		treeaxe: The TreeAxe 1.1.32.3
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		trulytreasures: Truly Treasures fabric-1.18.1-2.0.1
		victus: Victus 0.1.7+1.18
		voidtotem: VoidTotem (Fabric) 1.18.1-1.2.0
		voidz: VoidZ 1.0.5
		waystones: Waystones 9.0.4
		x-enchant: X-Enchant 1.18-8.6
		xp_storage: XP Storage 1.4.3+1.18
		xtraarrows: Xtra Arrows 1.8.1
		yigd: You're in Grave Danger 1.2.25
		yungsapi: YUNG's API 1.18-Fabric-36
		zombified: Zombified 1.3.0
	Server Running: true
	Player Count: 1 / 20; [class_3222['Summer_wind_'/55184, l='ServerLevel[world]', x=304.67, y=63.00, z=1030.24]]
	Data Packs: vanilla, Fabric Mods, data/Infinity-Datapack-CN.zip, data/Repurposed_Structures-More_Villagers_v4.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by CleverNucleus** [comment]
Hi there,
This issue was resolved in later updates that came in releases for Minecraft 1.18.2 and 1.19.2. I recommend updating to a newer version.
Thanks.

**Comment by bczhc** [comment]
> Hi there, This issue was resolved in later updates that came in releases for Minecraft 1.18.2 and 1.19.2. I recommend updating to a newer version. Thanks.

Hi. Sorry for the follow-up of this old issue. I'm playing modpack "Infinity" and it depends on PlayerEX 3.1.4. So I just politely ask can we have the fix for Minecraft 1.18.1 also? Thanks.
