### ISSUE TITLE
Balance Change suggestion

### ISSUE THREAD

**Issue by Mr-Syntax** [CleverNucleus/PlayerEx#104]
I think at the moment strenght is pretty OP and constitution & intelligence are a bit under appreciated

if you switch the armor increase from strength with the knockback resistance from constitution i think the balance would be much better

also intelligence if you could make them scale with the origin abilities, particularly the mod Orgins:Aspects and the wizards mod that would be awesome and make alot of sense

**Comment by CleverNucleus** [comment]
Hi there,
This can be customised using datapacks. Please see the Data Attributes [wiki](https://clevernucleus.github.io/dataattributes-1.18.2_home) and the PlayerEx [wiki](https://clevernucleus.github.io/playerex-1.18.2_home).
Thanks.
