### ISSUE TITLE
1.16.5 Forge HUD

### ISSUE THREAD

**Issue by Kleapy** [CleverNucleus/PlayerEx#109]
Is there any way to get the HUD to the classic one?

**Comment by CleverNucleus** [comment]
Hi there,
Please clarify - the 1.16.5 Forge release of the mod has a HUD that can be enabled/disabled.
The latest releases of PlayerEx for Fabric no longer has the HUD, instead it is a standalone mod, available [here](https://www.curseforge.com/minecraft/mc-mods/ex-hud).
Thanks.

**Comment by Kleapy** [comment]
I would like to thank you for telling me this, it seems i didnt do enough research. I found it and changed it. Sorry for wasting your time, thanks for help!

**Comment by CleverNucleus** [comment]
No problem.
