### ISSUE TITLE
Double stats on items appear with multiple mods.

### ISSUE THREAD

**Issue by githubbingitup** [CleverNucleus/PlayerEx#11]
"*Items with attack speed and attack damage modifiers now display the value of the modifier (i.e. the change that will be applied to those attributes) not the end result."

The conflict makes it so the vanilla stats and the new PlayerEx stats show at once:
https://i.imgur.com/ueCaGHV.png

Mods that I've found this problem with so far:
**WTHIT**/  **HWYLA**  - If "view mods" is turned on, this occurs.
**Tiered** - If you get an item that doesn't have any damage modifiers, then this occurs. When you get a damage modifier, it doesn't though. This mod combined with yours is absolutely perfect for making Minecraft into an RPG so compatibility between the two would be really nice for an RPG modpack. 
**sihywtcamd/ sihywtcamc** - These mods also cause it, which are great mods for increasing MC difficulty, which is really nice with a mod like PlayerEx that makes you more powerful. This way the game doesn't become a cakewalk.
**MC Dungeon Weapons/ Armor** - Seems to cause issues alongside this too. Gets very confusing.

I can probably find more mods that cause this. I think this feature just doesn't play well with other mods.
I think the feature is a tad confusing even when it all works right, especially since your attack speed is always negative as punching is faster.

Is there anyway to revert stats to display as the original? Would be nice to be able to just turn this off and not have to worry about conflict.

_*This mod also seems to stop weapons and armor from displaying the mod name at the bottom from WTHIT, though not a huge deal._

**Comment by CleverNucleus** [comment]
Hi there,
Thanks again for this in-depth bug report, I really appreciate it. I think I know what causes these issues, and maybe I'll add a config option to disable the change in item entity attribute modifier displays. The only reason why I changed it was because not changing it also results in the numbers being wrong, as good ol' vanilla hard codes them - meaning that if you actually deal 10 damage per hit, your sword may still say 6 or 7. 

Thanks again, keep them coming!

**Comment by githubbingitup** [comment]
Right, I get that the modified values are more accurate to what you're actually doing. 
Either solution sounds good to me. If I run into anything else I'll post it. :)

**Comment by CleverNucleus** [comment]
Fixed with v2.0.2 (I ended up just removing the tooltip fix in favour of implementing a better one that I can spend more time thinking over later; for now weapons will show vanilla/whatever mod changed tooltips).
