### ISSUE TITLE
Luck stat

### ISSUE THREAD

**Issue by nixord** [CleverNucleus/PlayerEx#112]
Hi again! This is not an issue but more of a question since I dont know how to contact you directly except through github. Does luck make you have better loot with everything? (including your other mod RelicEx)

**Comment by CleverNucleus** [comment]
Hi there,
The vanilla Luck attribute remains unchanged, and its effects can be viewed [here](https://minecraft.fandom.com/wiki/Luck). The [Luckiness](https://clevernucleus.github.io/playerex-1.18.2_content.html#attributes) attribute added by PlayerEx actually does nothing by itself; but increasing its value also increases the value of attributes that do have an effect, such as the vanilla Luck attribute. 

Tl;dr:

>Adds 1 × level to [attribute](https://minecraft.fandom.com/wiki/Attribute) generic.luck, making [loot table](https://minecraft.fandom.com/wiki/Loot_table) entries with a high quality score more likely, and entries with negative quality less likely. It also increases the chances of bonus_rolls occurring. Currently, only [fishing](https://minecraft.fandom.com/wiki/Fishing) uses quality. The new weight of each entry is floor(base_weight + quality * generic.luck). Negative levels decrease luck.

>Using a [fishing rod](https://minecraft.fandom.com/wiki/Fishing_rod) enchanted with [Luck of the Sea](https://minecraft.fandom.com/wiki/Luck_of_the_Sea) increases a [player](https://minecraft.fandom.com/wiki/Player)'s generic.luck attribute, but doesn't actually grant the Luck status effect.

Regarding RelicEx, the vanilla Luck attribute also makes it more likely for mobs to drop a relic item.

Hope that helps,
Thanks.

**Comment by nixord** [comment]
Thank you so much! Then... The Luckiness stat is almost a dump stat cause... The crit chance is ok but not game-changing unless you have some dex up and a LOT of points into Luckiness so you can use it for fishing and more relics... Ok nvm its not a dump stat. Int is (?

**Comment by CleverNucleus** [comment]
I would currently agree that Intelligence is a dump stat.
