### ISSUE TITLE
Connection to my fabric server

### ISSUE THREAD

**Issue by matveyvlone** [CleverNucleus/PlayerEx#113]
I use velocity proxy for my fabric server, and when i add it on client and on server, i try my best to connect to server and get this issue, sorry for my english 
![2023-02-25_20-18-00](https://user-images.githubusercontent.com/121692595/221370651-1a04c610-ae90-443f-b1fd-03144cab5019.png)
(data attributes installed)

**Comment by CleverNucleus** [comment]
Hi there,
I would refer you to [this](https://github.com/CleverNucleus/Data-Attributes/issues/10) issue.
Thanks.
