### ISSUE TITLE
[Feature Request] More config options

### ISSUE THREAD

**Issue by FeyrAmy** [CleverNucleus/PlayerEx#115]
Hello! I think that adding a config option that allows users to:

Set their starting stat values (0 by default)
Allow players to have a set amount of skill points (0 by default, alternate to feature request 1)
It would also be nice to move the level cap to a config option, though it may not necessarily be required., since this can be done via a datapack.

**Comment by CleverNucleus** [comment]
Hi there,
All the above is already configurable via datapacks - please see the [Data Attributes](https://clevernucleus.github.io/dataattributes-1.18.2_home) and [PlayerEx](https://clevernucleus.github.io/playerex-1.18.2_home) documentation for details. 
Thanks.
