### ISSUE TITLE
no drops of xp in certain chucks whatsoever

### ISSUE THREAD

**Issue by KlaraChaos** [CleverNucleus/PlayerEx#116]
i have the issue since im using playerex that certain chunks drop no xp whatsoever even if the setting for it is set to 100 for vanilla but even then its not droping xp in certain chucks even if i use xp bottles

**Comment by CleverNucleus** [comment]
Hi there,
Try the command `/playerex resetChunk` in the chunks where this is happening. If you're not already using the latest version of PlayerEx, please do so as it contains some fixes regarding this mechanic.
Thanks.

**Comment by KlaraChaos** [comment]
il try thanks

also im on the newest version 

its gonna be fun tho as a mayority of my spawn chucks are affected 2000 blocks on each side radius

might mbe usefull to make a command that massresets all chucks in case somone has a lot of chunks affected
