### ISSUE TITLE
Changing text from the GUI

### ISSUE THREAD

**Issue by aethylias** [CleverNucleus/PlayerEx#117]
Hello CleverNucleus! I don't know how to reach you aside from submitting an issue so I'm asking here.

How do you change the text from the GUI? Like the one that shows how much attack damage a point of Strength gives. 
I am not well versed at java but I can read some code so if you can guide me where to change it, it would be a huge help.

Also thank you for creating this awesome mod!

**Comment by CleverNucleus** [comment]
Hi there,
You can change these values using a datapack - please see the [Data Attributes](https://clevernucleus.github.io/dataattributes-1.18.2_home) and [PlayerEx](https://clevernucleus.github.io/playerex-1.18.2_home) documentation for details on how to do this.
Thanks.
