### ISSUE TITLE
PlayerEX Healthbar

### ISSUE THREAD

**Issue by Jrstepos** [CleverNucleus/PlayerEx#118]
From what I know, you should be able to change the PlayerEX health bar back to normal (I am using 1.16.5) using the config... which I have no idea how to do.

**Comment by CleverNucleus** [comment]
Hi there,
No problem - just navigate to your config file (in the `/config` folder wherever your game is installed) and there should be a file with the name `playerex-client` or similar. Open this file and inside should be an entry similar to `enableHUD` - set this to false.
Thanks.

**Comment by Jrstepos** [comment]
Perfect, thanks for the help!
