### ISSUE TITLE
[Feature Request]disable additional inventory tabs but not disable hotkey 

### ISSUE THREAD

**Issue by spake404** [CleverNucleus/playerex#120]
I tried to close inventory tabs, but it prevented me from using hotkeys to open the upgrade page. I hope they are not bound together

**Comment by CleverNucleus** [comment]
Hi there,
They are currently bound together, but I'll look into adding a client-side option to disable just the inventory tabs next update.
Thanks.

**Comment by CleverNucleus** [comment]
Implemented with `3.5.4+1.19.2`, available on Modrinth and pending approval on Curseforge.
