### ISSUE TITLE
[Feature Request] Ability to change what shows on the attributes gui

### ISSUE THREAD

**Issue by PixelatedBruh** [CleverNucleus/PlayerEx#121]
Hey there I wanted to be able to change what attributes could be shown on the gui pages.

I have a mod that supplies my with a new attribute projectile damage and I wanted to be able to show that in the place of the bonus ranged damage that this mod supplies as this attribute lets me scale the damage as i wanted. when i found out my only option was to change this in the mod myself it felt a bit silly for something this minor.

If this is not something you are willing to do I understand. It just makes sense to me that you would be able to show any attribute on the gui

**Comment by CleverNucleus** [comment]
Hi there,
My apologies for the late reply. You are correct in that to have your attribute displayed on the gui page you would need to develop an addon mod. I understand this frustration, especially when everything else is completely configurable - however, under the hood gui changes are much harder to add configuration for, and harder still when considering things like text scaling, localisations, and adding vs. overriding text.

That said, whatever scaling is implemented for your new projectile damage attribute, the existing bonus ranged damage attribute can likely be configured to scale in the same way and do the same things, which would negate the need to have a new attribute displayed.

Thanks.
