### ISSUE TITLE
 [Feature Request] Damage% fix and Config attribute customitzation

### ISSUE THREAD

**Issue by JonXL04** [CleverNucleus/PlayerEx#122]
I would like to be able to change more attributes from "+n" to "+m%" (for example: "+5% Armor" instead of "+0.5 Armor") to fix some issues regarding high level balancing.
Also, attributes like strength make useless using a weapon. i.e.: +10 damage -> diamond axe = 18 damage/1sec, your bare fist = 10/0.25sec damage = 40 damage/sec. Using % instead would make it proportional to your gear.

Being able to change the values(0.1->0.2), behavior(+% or +n) and content(adding attributes from other mods to some stats, like spell power to intelligence) would make it a lot easier to balance and customize modpacks/servers.

**Comment by CleverNucleus** [comment]
Hi there,
This is already configurable in the way that you have described using datapacks. Please see the [data attributes](https://clevernucleus.github.io/dataattributes-1.18.2_home) documentation for details. For some examples on datapack format, you can look inside the PlayerEx mod jar as well as visit the FAQ page for [PlayerEx](https://clevernucleus.github.io/playerex-1.18.2_faq.html).
Thanks.

**Comment by JonXL04** [comment]
Oh, ok thank you
