### ISSUE TITLE
Suggestion - Reset on death percentage

### ISSUE THREAD

**Issue by YumatanGames** [CleverNucleus/playerex#123]
I really like this mod and how it improves on the RPG aspect of the game, but I have an idea that could make it really better: 

Instead of Reset on death being either on or off, which is quite too draconian the way I see it, why don't allow players to choose a percentage of how many levels they'll keep on death? So if the config is set to keep, for example, 50% on death, they would lose half their levels as well as half of each attribute they spent points on. 

This would allow for server owners to better balance their desired difficulty, without being too harsh on players...

**Comment by CleverNucleus** [comment]
Hi there,
I like your suggestion. I have had similar previously but implementation is surprisingly not straightforward. I will look to include this feature in a future release.
Thanks.

**Comment by CleverNucleus** [comment]
Implemented with `3.5.4+1.19.2`, available on Modrinth and pending approval on Curseforge. See changelog for details.
