### ISSUE TITLE
Suggestions for lang

### ISSUE THREAD

**Issue by Annijang** [CleverNucleus/playerex#128]
Add "sound.playerex.level_up" and "sound.playerex.sp_spend" to the lang.

![image](https://github.com/CleverNucleus/playerex/assets/75552974/332d3edc-053d-41e9-9226-1766b55fbb2f)

**Comment by CleverNucleus** [comment]
Agree, will include in next release.

**Comment by CleverNucleus** [comment]
Implemented with `3.5.4+1.19.2`, available on Modrinth and pending approval on Curseforge.
