### ISSUE TITLE
[Suggestion] Projectile Damage integration

### ISSUE THREAD

**Issue by muon-rw** [CleverNucleus/playerex#131]
Currently, when both mods are installed, `playerex:ranged_damage` is (I think) just added to `projectile_damage:generic`, and the total damage calculated by both  is multiplied by `playerex:ranged_crit_damage` (not factoring in the variable arrow damage factors). This works, but what displays on the combat attribute page is just bonus damage, and isn't very clear or as elegant as the current implementation with `generic.attack_damage`, where the attribute updates based on the equipped weapon and total stats to give a relatively accurate value of the actual attack damage. 

This is especially confusing in instances where the projectile damage attribute is scaled, for instance, a bow that has 12 damage instead of 6 - the player probably expects their combat attributes page to reflect something but it doesn't

I'd like to suggest implementing Projectile Damage as a dependency (it's a very lightweight mod), and replacing "Bonus Damage" on the combat attributes page with "Ranged Damage" (which is just the total ranged damage as already calculated by projectile_damage:generic+playerex:ranged_damage, or however it's actually calculated.)

**Comment by CleverNucleus** [comment]
Hi there,
Agree with everything you've said - plan to do this in next update (for 1.19.2).
Thanks.

**Comment by CleverNucleus** [comment]
Implemented with `3.5.4+1.19.2`, available on Modrinth and pending approval on Curseforge.
