### ISSUE TITLE
PlayerEX level is dropping to 1 even if "Reset On Death" option set to 0%

### ISSUE THREAD

**Issue by Fleyzi** [CleverNucleus/playerex#135]
It's strange, but I set "Reset On Death" setting to 0 percent, but I still getting level 1 when my character dies

Here's video: https://streamable.com/kkbtip
Log file: https://gist.github.com/Fleyzi/b4a9b67a8eb7ce97f288da8ebb6ec653

PlayerEx 3.5.4
Minecraft 1.19.2
Fabric Loader 0.14.21
Fabric API 0.76.0

**Comment by CleverNucleus** [comment]
![image](https://github.com/CleverNucleus/playerex/assets/8604539/a66ca6c3-2723-4ff0-b17c-5d517f73fc24)
You are shown to have level zero here no?

**Comment by Fleyzi** [comment]
Oops, that messed up. Anyways the Level (and all attributes) dropping to their default values even I set "Reset On Death" to 0 percent (that means "false").

**Comment by CleverNucleus** [comment]
Hi there,
This is working as intended. When the config option is set to zero, everything should be reset to their defaults and your level should drop to zero - as it does in the video. When the config option is set to 100, you don't lose anything on death and your level remains the same. The config option percentage is *the percentage of attributes kept after death*, not lost.

See the changelog here:
![image](https://github.com/CleverNucleus/playerex/assets/8604539/6e017688-0447-4014-a54f-8ccf00050930)
