### ISSUE TITLE
Crash related to playerex:heal_amplification attribute being missing? (Fabric 1.16.5 playerex-2.0.5-1.16.5)

### ISSUE THREAD

**Issue by LightningFerix** [CleverNucleus/PlayerEx#139]
Not Enough Crashes thinks Playerex is causing a crash for the client
[crash-2023-08-06_18.25.23-client.txt](https://github.com/CleverNucleus/playerex/files/12271176/crash-2023-08-06_18.25.23-client.txt)

**Comment by LightningFerix** [comment]
Wanted to clarify that this is in Fabric 1.16.5 with this specific mod file: playerex-2.0.5-1.16.5

**Comment by CleverNucleus** [comment]
Hi there,
That version is no longer supported. 
Thanks.
