### ISSUE TITLE
Game crashes when friend shoots crossbow

### ISSUE THREAD

**Issue by Poolio10** [CleverNucleus/PlayerEx#15]
My friends and I are playing with the mod in the pack and one of us uses a crossbow with high crit chance and damage. Any time he shoots near someone, their game crashes outright. I included the crash report 

[crash-2021-07-15_23.39.19-client.txt](https://github.com/CleverNucleus/PlayerEx/files/6827880/crash-2021-07-15_23.39.19-client.txt)

**Comment by CleverNucleus** [comment]
Hi there,
Just to be clear, the player *near* to the one who shot the crossbow crashes, not the shooter?

**Comment by Llightfoot135** [comment]
I was the one firing, did not crash

**Comment by CleverNucleus** [comment]
Thanks, I'll see if I can fix this one asap.

**Comment by CleverNucleus** [comment]
This should now be fixed in the latest release (v2.0.5).
