### ISSUE TITLE
[Feature Request] Add placeholders for Box of Placeholders addon

### ISSUE THREAD

**Issue by elhertz** [CleverNucleus/PlayerEx#17]
[Box of Placeholders](https://www.curseforge.com/minecraft/mc-mods/box-of-placeholders) - [PlaceholderAPI](https://placeholders.pb4.eu/)
It'd be nice to have some quick info on the tablist or scoreboard -- and maybe a placeholder to get info from other users? that way you could create a player top-list on the scoreboard using normal placeholders and nested placeholders:
- %playerex_level_top_1% = %playerex_level{playerex_level_top_1}% 
- %playerex_level_top_2% = %playerex_level{playerex_level_top_2}% 
- %playerex_level_top_3% = %playerex_level{playerex_level_top_3}% 
- etc
 
(_StyledScoreboards is still in dev afaik but you could do this using [StyledPlayerList](https://www.curseforge.com/minecraft/mc-mods/styled-player-list)_)

**Comment by CleverNucleus** [comment]
Hi there,
I'm wholly unfamiliar with this, but if you give me some time I can look into it and get back to you. Or if I'm taking too long, feel free to make a pull request. 
Thanks.

**Comment by CleverNucleus** [comment]
Just following up,
I've been playing around with Placeholders a bit, but I don't know how to make a scoreboard using any of the placeholders, nor do I know what _exactly_ is required to do so. What I can do is create commands that interpret my custom placeholders, such as: 

`/playerex string <placeholder>`

Similar/equivalent to the default `/boxofplaceholders string <placeholder>`

Could you specify how you'd go about creating your scoreboard so I could replicate that and use it for testing?
Otherwise I'll admit I'm a little lost, this is unfamiliar to me still and I can only invest so much time learning new things.
Thanks.

**Comment by elhertz** [comment]
Thank you for taking my request in consideration!
Currently you can use the placeholders on [StyledPlayerList](https://www.curseforge.com/minecraft/mc-mods/styled-player-list) and [StyledChat](https://www.curseforge.com/minecraft/mc-mods/styled-chat)
I recommend you joining the [discord](https://discord.com/invite/AbqPPppgrd) of the owner of Box of Placeholders 

This is my current config on StyledPlayerList
```
{
  "CONFIG_VERSION_DONT_TOUCH_THIS": 1,
  "_comment": "Before changing anything, see https://github.com/Patbox/StyledPlayerList#configuration",
  "defaultStyle": "default",
  "updateRate": 20,
  "switchMessage": "Tu TAB ha sido cambiado a: <gold>${style}</gold>",
  "unknownStyleMessage": "<red>Ese estilo no existe!</red>",
  "permissionMessage": "<red>No tienes permisos!</red>",
  "changePlayerName": true,
  "playerNameFormat": " %luckperms:prefix% %player:displayname% <color:#D12222>%player:health%❤</color>",
  "updatePlayerNameEveryChatMessage": false,
  "playerNameUpdateRate": 20,
  "permissionNameFormat": []
}
```
It looks like this:
![It looks like this](https://i.imgur.com/U9AgfFs.png)
(don't mind the null thingy, i'm just testing placeholders)

But if you add PlayerEx placeholders support it would look like this:
![But if you add PlayerEx placeholders support it would look like this](https://i.imgur.com/RvdADhI.png)

This would be the config:
```
{
  "CONFIG_VERSION_DONT_TOUCH_THIS": 1,
  "_comment": "Before changing anything, see https://github.com/Patbox/StyledPlayerList#configuration",
  "defaultStyle": "default",
  "updateRate": 20,
  "switchMessage": "Tu TAB ha sido cambiado a: <gold>${style}</gold>",
  "unknownStyleMessage": "<red>Ese estilo no existe!</red>",
  "permissionMessage": "<red>No tienes permisos!</red>",
  "changePlayerName": true,
  "playerNameFormat": " %luckperms:prefix% Lvl%playerex:level% %player:displayname% <color:#D12222>%player:health%❤</color>",
  "updatePlayerNameEveryChatMessage": false,
  "playerNameUpdateRate": 20,
  "permissionNameFormat": []
}
```
----------------------------------------
That's an example, but you can do the same with StyledChat and all of patbox's plugins. Feels like we are in bukkit, right? it's amazing.
Also it would be nice to have placeholders to get info from other players so when the StyledScoreboard gets released you can make a level top from playerex, how cool would that be? (you could make something like that adding lines to the tab too, but the scoreboard is nicer for things like that)

This is an example of what you can do with placeholders and StyledPlayerlist:
![This is an example of what you can do with placeholders and StyledPlayerlist](https://media.discordapp.net/attachments/783411467914969168/882479485847490660/2021-08-12_00.22.05.png?width=1286&height=688)
(img is not mine, someone shared it on patbox's discord)

**Comment by CleverNucleus** [comment]
This is great, I really appreciate you taking the time to write out such a detailed comment. I'll continue working on it. 
Thanks.

**Comment by CleverNucleus** [comment]
I've added some placeholders and a page for them on the wiki. Feel free to suggest more that I can add in the future.

**Comment by elhertz** [comment]
Wow you're amazing! I'll request for your mod to be added to the [list](https://placeholders.pb4.eu/user/mod-placeholders/) (_if that's alright with you_)
Thanks!

**Comment by elhertz** [comment]
So I got the chance to finally open my server and after some requests from my friends I wanted to give a couple suggestions;

- First, to show the all time top players instead of the players that are currently connected.
- Add a placeholder to show the level of player in a specific top position. For that I think `%playerex:level_top/x%` should be renamed to `%playerex:name_top/x%` and you should create a %playerex:level_top/x% placeholder to show the level.
Example:
`%playerex:name_top/1%` = Hertz
`%playerex:level_top/1%` = 100

Thank you. I love your mod, 0 bugs so far!

**Comment by CleverNucleus** [comment]
Hi there,
These are some good suggestions, I think I can implement them without too much trouble.

Just so that I understand correctly, you want `%playerex:name_top/x%` and `%playerex:level_top/x%` to include offline players in addition to currently connected ones?
Thanks.
