### ISSUE TITLE
Missing dependency information in manifest

### ISSUE THREAD

**Issue by Janrupf** [CleverNucleus/PlayerEx#18]
The mod depends hard on `Data Attributes` as mentioned on the CurseForge page (and well, seen by logs when starting without it). `Data Attributes` should be added to the manifest as a dependency:
https://github.com/CleverNucleus/PlayerEx/blob/287b7ca28d01d13584978a82f502278486d7155e/src/main/resources/fabric.mod.json#L42-L47

I also don't think this belongs here:
https://github.com/CleverNucleus/PlayerEx/blob/287b7ca28d01d13584978a82f502278486d7155e/src/main/resources/fabric.mod.json#L48-L50

**Comment by CleverNucleus** [comment]
Ah well spotted - I'll amend that in the next release. Thanks.

**Comment by CleverNucleus** [comment]
Fixed.
