### ISSUE TITLE
[Feature Request] starting attributes

### ISSUE THREAD

**Issue by elhertz** [CleverNucleus/PlayerEx#19]
I think it would be good to have an option to set my players' starting health to make things more interesting.
Imagine starting with 1 heart and a slow walking/running speed, also in hardcore mode, that would be amazing!

**Comment by CleverNucleus** [comment]
You can. Please see [Data Attributes](https://github.com/CleverNucleus/DataAttributes/wiki).

**Comment by elhertz** [comment]
Wow that's amazing! thanks
