### ISSUE TITLE
Plans to make basic functions further configurable for coding-illiterates?

### ISSUE THREAD

**Issue by StygianEmperor** [CleverNucleus/PlayerEx#2]
This mod seems pretty great to begin with, but there's always a few things here or there with any mod I'd want to tinker with, like making Intelligence boost enchantment bonuses or elemental (fire) damage dealt or something. Unfortunately I can't find the attention span to learn other languages (coding _or_ speaking) so just about all the script I write is reverse-engineered from things that _almost_ do what I want already and occasionally looking up definitions where I can find them. Needless to say my success rate is poor.

Not necessarily the ability to add _those_ stats, specifically (since you probably would have already included them if they were that easy), but **do you have any intentions to make more of the core of this mod editable via a plain-English** (and/or other languages) **config file?** Even if it's just scaling more numbers, or maybe which attributes increase which stats?

Sorry for rambling.

**Comment by CleverNucleus** [comment]
Hi there, 
>Intelligence boost enchantment bonuses or elemental (fire) damage dealt
>just scaling more numbers, or maybe which attributes increase which stats

These can be done with the API, and I fully agree with you along that theme (cool!).

I have no plans at the moment to make adding attributes or behaviours a configurable thing  (such as datapacks) outside of the Java environment. I understand your sentiment, but the reality is that if you do not understand how to code minecraft mods or you cannot get someone to code them for you, you're out of luck.

That said, by looking through this repository you may find plenty of examples to reverse engineer (in addition to the API wiki). 

Thank you for your interest.
