### ISSUE TITLE
Dexterity scaling melee damage incorrectly

### ISSUE THREAD

**Issue by Shads404** [CleverNucleus/PlayerEx#21]
Latest version on fabric.  Tested with  No other mods.  Brand new character and world.

23 points into dexterity will allow you to one hit vindicators (normal difficulty) with a wooden axe, every single time.  I don't believe this is intended behavior of dexterity scaling at all.

Combat tab shows attack dmg of 7 as per the base for axe, speed of  3.09 and crit dmg as 203% so my guess here is that every single hit is crit?   If i don't use full dmg attacks the 1 tap goes away

**Comment by EmoBubbleGum** [comment]
yea.. seems to be the issue across any use of this mod.... makes it more or less unusable.

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate you bringing this to my attention. I have fixed the issue and will be deploying the fix in the next release, hopefully tomorrow or the day after.

**Comment by CleverNucleus** [comment]
Fixed in latest release, 3.0.3.
