### ISSUE TITLE
Reset on death not working

### ISSUE THREAD

**Issue by Imcaam** [CleverNucleus/PlayerEx#25]
What title says, 

I am currently on version 3.0.3 for 1.17.1, I have tried on different worlds, changing the setting on and off (restarting the game) and on creative gameworlds but my character never resets the levels. Am I understanding the function wrong?

Thanks

**Comment by CleverNucleus** [comment]
Hi there,
I've verified your issue; I'll release a fix asap.
Thanks.

**Comment by CleverNucleus** [comment]
Want to close this manually when I upload the file to curseforge.
