### ISSUE TITLE
Server Crashing when Player joins

### ISSUE THREAD

**Issue by Amitiy** [CleverNucleus/PlayerEx#27]
Hello! In multiplayer the server crashes when a specific player joins, we had fixed the issue by generating a new world, however the issue is now caused by another player.

Here is the crash log from the server.

[crash-2021-09-15_22.10.38-server.txt](https://github.com/CleverNucleus/PlayerEx/files/7173662/crash-2021-09-15_22.10.38-server.txt)

**Comment by CleverNucleus** [comment]
Hi there,
This is a strange one; hard to diagnose a `java.lang.Error`. I'm not sure that I can reliably reproduce this issue, so I can't say I'm very confident that I'll be able to resolve this one, especially considering all the possible mod interactions.

If this happens again, I suggest trying to delete the specific player's data file before deleting the world (if you haven't already tried that).
Thanks.

**Comment by Amitiy** [comment]
Ah, It appears to be a weird interaction from playerex with Eldritch Mobs mod, mostly caused by the Eldritch mobs mod itself.  I have found this out on the modpack's discord. Thank you for the prompt reply though!
