### ISSUE TITLE
Crash on Linving Entity Loot

### ISSUE THREAD

**Issue by Slither88** [CleverNucleus/PlayerEx#3]
Hi. Please see the below crash logs. It seems that the mod is struggling to add loot to newly spawned creatures. These happen randomly as we explore on the server.

[crash-2021-01-24_08.38.33-server.txt](https://github.com/CleverNucleus/PlayerEx/files/5861828/crash-2021-01-24_08.38.33-server.txt)
[crash-2021-01-24_09.38.47-server.txt](https://github.com/CleverNucleus/PlayerEx/files/5861829/crash-2021-01-24_09.38.47-server.txt)

This is on 1.16.4 with forge 35.1.37 with version 1.1.5 of PlayerEX installed

**Comment by CleverNucleus** [comment]
Hi there,
It should now be fixed in the latest release (1.1.6).
Thanks.

**Comment by Slither88** [comment]
Thank you kindly!

**Comment by Hexonoid** [comment]
I am having this exact crash on MC v1.16.4 with forge v35.1.37 and 1.1.7 of PlayerEX, which is after this issue was supposedly fixed.

[crash-2021-01-24_08.38.33-server.txt](https://github.com/CleverNucleus/PlayerEx/files/6059267/crash-2021-01-24_08.38.33-server.txt)

**Comment by CleverNucleus** [comment]
> I am having this exact crash on MC v1.16.4 with forge v35.1.37 and 1.1.7 of PlayerEX, which is after this issue was supposedly fixed.
> 
> [crash-2021-01-24_08.38.33-server.txt](https://github.com/CleverNucleus/PlayerEx/files/6059267/crash-2021-01-24_08.38.33-server.txt)

Hi there,
The crash report you submitted is using PlayerEx 1.1.5. Please double check that your version is 1.1.7. If in any doubt over the version, open the mod jar and navigate to the mods.toml file located in the META-INF folder. 
Thanks.

**Comment by Hexonoid** [comment]
> > I am having this exact crash on MC v1.16.4 with forge v35.1.37 and 1.1.7 of PlayerEX, which is after this issue was supposedly fixed.
> > [crash-2021-01-24_08.38.33-server.txt](https://github.com/CleverNucleus/PlayerEx/files/6059267/crash-2021-01-24_08.38.33-server.txt)
> 
> Hi there,
> The crash report you submitted is using PlayerEx 1.1.5. Please double check that your version is 1.1.7. If in any doubt over the version, open the mod jar and navigate to the mods.toml file located in the META-INF folder.
> Thanks.

Hi CleverNucleus, I doubled checked the version, and it is indeed 1.1.7. Line 8 in the crash report under ticking entity also says playerex:1.1.7
at com.github.clevernucleus.playerex.init.EventHandler.onLivingLoot(EventHandler.java:395) ~[playerex:1.1.7] {re:classloading}

**Comment by CleverNucleus** [comment]
> Hi CleverNucleus, I doubled checked the version, and it is indeed 1.1.7. Line 8 in the crash report under ticking entity also says playerex:1.1.7
> at com.github.clevernucleus.playerex.init.EventHandler.onLivingLoot(EventHandler.java:395) ~[playerex:1.1.7] {re:classloading}

When I open this text file that you have linked, line 8 is the following:
`	at com.github.clevernucleus.playerex.init.EventHandler.onLivingLoot(EventHandler.java:363) ~[playerex:1.1.5] {re:classloading}`

**Comment by Hexonoid** [comment]
> > Hi CleverNucleus, I doubled checked the version, and it is indeed 1.1.7. Line 8 in the crash report under ticking entity also says playerex:1.1.7
> > at com.github.clevernucleus.playerex.init.EventHandler.onLivingLoot(EventHandler.java:395) ~[playerex:1.1.7] {re:classloading}
> 
> When I open this text file that you have linked, line 8 is the following:
> ` at com.github.clevernucleus.playerex.init.EventHandler.onLivingLoot(EventHandler.java:363) ~[playerex:1.1.5] {re:classloading}`

[crash-2021-03-01_14.49.28-server.txt](https://github.com/CleverNucleus/PlayerEx/files/6064332/crash-2021-03-01_14.49.28-server.txt)
[crash-2021-03-01_14.44.16-server.txt](https://github.com/CleverNucleus/PlayerEx/files/6064333/crash-2021-03-01_14.44.16-server.txt)

Sorry about that, that was an older one, these two should be with 1.1.7

**Comment by Hexonoid** [comment]
Also, from what I've seen, this crash triggers every time a creeper explodes. I just tried disabled creeper spawn to see if the crash stops, and so far nothing yet.

**Comment by CleverNucleus** [comment]
Released a hotfix - 1.1.7.5. This _should_ have fixed the issue, but I've said that before so..

**Comment by Hexonoid** [comment]
> Released a hotfix - 1.1.7.5. This _should_ have fixed the issue, but I've said that before so..

Thank you very much, I will try it out!
