### ISSUE TITLE
[Feature Request] Use commands on offline (disconnected) players

### ISSUE THREAD

**Issue by elhertz** [CleverNucleus/PlayerEx#31]
Allow commands to be used on disconnected players.

This what happens when you use a command on players that's not currently online:
![example](https://i.imgur.com/Wg1VsUm.png)

**Comment by CleverNucleus** [comment]
What commands specifically? Do you mean vanilla commands or playerex commands (i.e. `/playerex levelup ..`?

**Comment by elhertz** [comment]
I tried reseting someone's level so they wouldn't appear on the top (they stopped playing) and realized that I couldn't do it if they weren't online when executing the command. Tried the levelup and it doesn't work either.

**Comment by elhertz** [comment]
Oh that's brilliant. Thank you!
