### ISSUE TITLE
apply new config changes

### ISSUE THREAD

**Issue by Nika-m** [CleverNucleus/PlayerEx#35]
in config file there is written 
"#These only have an affect when a player is first joining the world."
where are those settings saved so I can remove them and apply updated config changes?
I removed all player data and capabilities.dat from world but, when joining changes are not updated, wanted to change default healths from 3 healths to 10 as it is in vanilla minecraft

**Comment by CleverNucleus** [comment]
I'm no longer providing support for Forge. 
Thanks.

**Comment by Nika-m** [comment]
I just asked where does mod save those data
