### ISSUE TITLE
Health issue everytime we log in.

### ISSUE THREAD

**Issue by BartzV** [CleverNucleus/PlayerEx#37]
Everytime we log in Minecraft saves que current health capped at base max health, not the modded one.
For Example, if i have 24/24hp and log out, when i log in again, my char will have 20/24hp.

**Comment by CleverNucleus** [comment]
Hi there,
Thank you for raising this issue, please include the following details: 
 - mod version
 - Fabric API version
 - List of other mods installed

Additionally, I assume this is on a server not single player? Please correct me if that's wrong.
Thanks.

**Comment by BartzV** [comment]
Hello. No, it is not a server, is only singleplayer. I have the latest
version at this date (recently downloaded, 3.0.7) and i playing Minecraft
1.17.1 with Fabric 0.11.7. Everytime i quit the game and reenter, my char
has the base health, like if i taken damage before quit.

**Comment by Minionade** [comment]
This is also happening on a server, it even happens when leveling up constitution; you'll go from 25/25 to 20/26 upon adding the extra point.

**Comment by CleverNucleus** [comment]
It's a bug with Data Attributes. It's fixed in the soon-to-be release for minecraft 1.18; PlayerEx will take longer to port.

**Comment by CleverNucleus** [comment]
Fixed with 1.18.1 update.
