### ISSUE TITLE
Fishing bug 1.16.5

### ISSUE THREAD

**Issue by Eugene21040** [CleverNucleus/PlayerEx#38]
Good afternoon, I'm playing on version 1,16,5 and found a bug,
If you pump more than 90 luck, then there is no way to catch a fish
the float sinks but when the fish is hooked, there is no
I have not tested other stats, but I noticed a problem only with luck

**Comment by CleverNucleus** [comment]
Hi there,
Unfortunately I'm only able to provide support for the latest release, as stated on the mod page. If this issue persists in the latest version, it can be remedied by using datapacks to gate the luck attribute.
Thanks.
