### ISSUE TITLE
Suggestion: Integration with FancyHUD

### ISSUE THREAD

**Issue by AuroraHydroid** [CleverNucleus/PlayerEx#40]
Thank you for the excellent mod! 
I would like to make a suggestion: please allow support for FancyHUD, if you plan on supporting the 1.16.5 version of this mod after porting to 1.18

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate your comment, however I will only be supporting 1.18. Furthermore, FancyHUD is for Forge, which is deprecated with PlayerEx.
Thank you though.
