### ISSUE TITLE
Experience for Skill levels are dependent on minecraft experience gain?

### ISSUE THREAD

**Issue by JeNoVaViRuS** [CleverNucleus/PlayerEx#43]
I assume that collecting the Minecraft experience orbs are the base for adding experience to the skill levels of this mod?
Since this mod is used mostly in adventure/RPG packs I would like to point out an issue I have experienced on my server:

The mod "Apotheosis" has an enchantment that converts drops into extra xp. If you then enchant a sword with additional stuff like Looting (which is avaailable up to lvl 7 because of Apotheosis) you get 20 levels per enderman kill with such a sword.
This wouldn't be a problem in itself but this makes gaining hundreds of levels easily possible in PlayerEx meaning it's just a matter of minutes.

Is it possible for you to code it to use the base xp of the mobs regardless of collected xp?

**Comment by CleverNucleus** [comment]
Hi there,
