### ISSUE TITLE
PlayerEx attributes still allow spending of skill points upon reaching cap.

### ISSUE THREAD

**Issue by raziehEP** [CleverNucleus/PlayerEx#45]
If you set a maxValue for a given attribute, the GUI does not function as expected. 

For example: if we set the max constitution to 20, upon reaching that in the GUI, you can still click the + button. Skill points are consumed, but constitution does not increase past 20. However, Level seems to work as intended and the + button greys out and can not be clicked upon reaching the cap. 

I would expect stats to not allow skill points to be placed upon reaching their cap.
Core: fabric-api-0.46.0+1.18
Version: playerex-3.1.0-1.18.1 and dataattributes-1.1.4-1.18.1
Overrides: done via datapack

**Comment by CleverNucleus** [comment]
Hi there,
I've verified this; I'll release a fix asap.
Thanks.
