### ISSUE TITLE
Server Crashing on Startup

### ISSUE THREAD

**Issue by Plastogerm** [CleverNucleus/PlayerEx#48]
Hello!
I'm trying to set-up a 1.18.1 server which includes this mod and its dependencies, unfortunately as it turns out, the server runs for about 2-10 seconds before shutting down.

The logs returned the following:
<html>
<body>

[19:12:38] [Server thread/ERROR]: Encountered an unexpected exception
--
1891 | java.lang.NoSuchMethodError: 'dev.onyxstudios.cca.api.v3.component.ComponentContainer net.minecraft.class_5268.getComponentContainer()'
1892 | at net.minecraft.server.MinecraftServer.handler$zne000$onEndTick(MinecraftServer.java:3760) ~[server-intermediary.jar:?]
1893 | at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:861) ~[server-intermediary.jar:?]
1894 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[server-intermediary.jar:?]
1895 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
1896 | at java.lang.Thread.run(Thread.java:833) [?:?]
1897 | [19:12:38] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2022-02-03_19.12.38-server.txt

</body>
</html>

I suspect it has something to do with Cardinal Components API changing their maven group from `io.github.onyxstudios.Cardinal-Components-API` to `dev.onyxstudios.cardinal-components-api`. Unfortunately, people with similar issues as I do have opened an issue on their repository, but nothing has yet to be fixed on their end.

Do I have to wait for the creators of CC API to fix this? Or are there any workarounds?

If it matters, I've tried using Cardinal Components API v.4.0.0, 4.1.0, and the latest upload; (which was 13 hours ago) 4.1.1.

**Comment by CleverNucleus** [comment]
Hi there,
I've verified this; it could be because of their switch. I find it odd that the jar-in-jar v4.1.0 works, but the full v4.1.0 release does not. If I had to hazard I guess I would suspect an issue with PlayerEx, but seeing as others are encountering the same problem I'm not too sure. I'll work towards a fix; it may just be a case of updating to require the latest version of CCA or waiting to see if it is indeed a problem on their end and they output a fix.
Thanks for bringing this to my attention.

**Comment by Plastogerm** [comment]
This issue is no more! I've just finished about an hour long play session with PlayerEx using the latest CC API version v4.1.2, and have came across no errors or crashes from either of them.

Gotta say I really love your mod so far, Nucleus! I'm really excited to further customize my character stats early on around my modded arsenal. Gonna close this issue now though, thank you for the time.
