### ISSUE TITLE
[Bug and Request] Compatability with first aid?

### ISSUE THREAD

**Issue by ConqAra** [CleverNucleus/PlayerEx#5]
Adding points to strength with first aid on completely bugs out the screen. It attempts to heal the player while first aid fights it. Can there be an easy config option to alter this by having the option to get rid of health regen on strength? For those who want to use first aid with the bandage healing system, the healing AMPLIFICATION is very nice, but the lack of turning off regeneration with a config will destroy the mod's compatibility unless you sacrifice the bandage system.

**Comment by CleverNucleus** [comment]
Hi there,
I am actively working towards making the mod data driven (datapacks), which would solve issues like these and increase customisability and compatibility. This is a ways off and I'm aiming for something around 1.17 if not a bit earlier. 

Until then, I will release a version with a config option specifically for enabling/disabling default adder functions (like strength>>health regen).

I'll leave this here, and close this issue upon released.
Thanks.

**Comment by CleverNucleus** [comment]
Released version 1.1.7, which includes configuration options to enable/disable all adder/modifier functions (by default these are enabled). Of course this is still a stopgap measure, but will stick around until datadriven content is implemented.
