### ISSUE TITLE
No attibutes

### ISSUE THREAD

**Issue by liamshannon31** [CleverNucleus/PlayerEx#51]
I think when I did /clear to kill all the nearby mobs it broke my skills, I cannot gain levels I'm on level 0 and when I try to use commands to gain levels it says I have no Attribute levels. 1.17 Medieval Curse Forge.

**Comment by CleverNucleus** [comment]
Hi there,
Just to confirm, you are playing on Minecraft 1.17.1 yes?
Thanks.

**Comment by CleverNucleus** [comment]
Assumed as Minecraft 1.17.1 and hence not applicable to the latest release.
