### ISSUE TITLE
Here's russian translation for 1.16.5

### ISSUE THREAD

**Issue by MiniRaptor** [CleverNucleus/PlayerEx#52]
[ru_ru.zip](https://github.com/CleverNucleus/PlayerEx/files/8111320/ru_ru.zip)

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate your contribution; however, I am only supporting the latest release i.e. for Minecraft 1.18.1, as per the [curseforge](https://www.curseforge.com/minecraft/mc-mods/playerex) mod page. This means that I am not outputting new releases for Minecraft 1.16.5 - I apologise if that was not made clear. 

If you still wish to add Russian language support for the latest releases (Minecraft 1.18), then you are of course still welcome to do so. That said, if you want to use the translation you have provided with Minecraft 1.16.5, you can do so with a resource pack.
Thanks.

**Comment by CleverNucleus** [comment]
Closing as have now received Russian translation for relevant version.
