### ISSUE TITLE
Attributes randomly resetting on world save/exit

### ISSUE THREAD

**Issue by Desempregago** [CleverNucleus/PlayerEx#54]
![image](https://user-images.githubusercontent.com/14002834/156028722-ebd1f26b-c441-40e0-b7e3-dbf938b29751.png)

PlayerEx 3.14
Minecrat 1.18.1

**Comment by CleverNucleus** [comment]
Hi there,
Could you specify what version of Data Attributes you are using? Additionally, if you are using other mods that may have an impact on attributes (such as AttributeFix) please make them known as well.
Thanks.

**Comment by Desempregago** [comment]
I'm using Data Attributes 1.1.5.
AttributeFix is present (version 13.0.5), but because it's an optional dependency from ArmorPoints++ (health/armor overlay alternative)

**Comment by Desempregago** [comment]
gonna test without AttributeFix to see if it is a conflict with it.

**Comment by CleverNucleus** [comment]
Okay thank you for the information, I'll look into it. I'll just note that being a random occurrence makes this difficult to replicate and therefore troubleshoot.

**Comment by Desempregago** [comment]
Yeah, apparently it was being caused by Attribute Fix, since I tried to reproduce it 3 times without it already and the stats are being kept properly

![image](https://user-images.githubusercontent.com/14002834/156082736-2cd3ab0e-7b0c-477b-8f6b-219803a25ae9.png)

**Comment by CleverNucleus** [comment]
Ah okay, in that case I'll close this issue now. If it does manifest again without AttributeFix don't hesitate to reopen the issue.
Thanks.
