### ISSUE TITLE
Hey! We have translated the mod into Russian. ver 1.18.1

### ISSUE THREAD

**Issue by MrTYZzik** [CleverNucleus/PlayerEx#55]
We have translated the mod into **Russian**. I attach a file with Russian text. Add it to the next version of the mod.
[Google drive link](https://drive.google.com/file/d/1VOcrlLpB_Nu3wvML9-Y7fv8rsPcbcLtE/view?usp=sharing)

**Comment by MrTYZzik** [comment]
I tried to translate the mod as correctly as possible for the Russian language.

**Comment by CleverNucleus** [comment]
Hi there,
That's awesome, I'll include it in the next release.
Thanks!
