### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by Ozakinn** [CleverNucleus/PlayerEx#58]
It seems that PlayerEx isn't properly working with 1.18.2.
It would be nice to use with support of latest version.
Best rpg skills so far. Hope we can get 1.18.2 support soon. Thanks!

**Comment by CleverNucleus** [comment]
Hi there,
You're correct, it is incompatible with Minecraft 1.18.2 at present. I have taken a (small) break from modding  to focus on other projects, although I'm expecting to be able to continue modding at the start of May.

Thanks!

**Comment by Monster-Zer0** [comment]
looking forward to the 1.18.2 version. I have big plans.

**Comment by CleverNucleus** [comment]
Hi there,
Minecraft 1.18.2 now has a release for PlayerEx, albeit with lots of mod conflicts due to lack of testing. I will slowly be attempting to resolve these.
Thanks.
