### ISSUE TITLE
Starting attributes are added to existing characters when editing config file

### ISSUE THREAD

**Issue by Sazuzaki** [CleverNucleus/PlayerEx#59]
Hey, whenever I edited the starting attributes to a stat (say constitution) in the config file, it applies to existing characters. For example, I have 15 CON, and change the starting attribute to 20 in the config file. Now I have 35 CON (15+20=35) without it actually affecting my health, but still annoying nonetheless as I don't have an accurate showcase of my CON stat. 

Thanks!

**Comment by CleverNucleus** [comment]
Hi there,
Could you please specify what version of the mod you are using?
Thanks.
