### ISSUE TITLE
Health bar

### ISSUE THREAD

**Issue by thatdude69420** [CleverNucleus/PlayerEx#6]
Hi Mr CleverNucleus,

I love your mod. U did fantastic work here. Good job!! But if I may; I really like the old health bar (with the vanilla hearts) rather than your streamlined (one single bar). Personal preference you know? Is there anyway to revert that one specific detail. Love everything else!

**Comment by CleverNucleus** [comment]
Hi there,
I understand; I will look to add a configuration option to enable/disable specific HUD elements.
Thanks.
