### ISSUE TITLE
A way to cap levels? 

### ISSUE THREAD

**Issue by drakosoldier298** [CleverNucleus/PlayerEx#60]
I was wanting to cap my players constitution dex etc to 100, but cant seem to find out how.

**Comment by CleverNucleus** [comment]
Hi there,
You can use a datapack to achieve this - specifically, you need to create attribute [overrides](https://github.com/CleverNucleus/DataAttributes/wiki/Overrides) and set the attribute's maxValue to 100 (or whatever you want).

See the Data Attributes [wiki](https://github.com/CleverNucleus/DataAttributes/wiki) for more information.
Thanks.
