### ISSUE TITLE
Screen twitching when the health regens

### ISSUE THREAD

**Issue by VictorSPM** [CleverNucleus/PlayerEx#61]
as in titled, i am also playing it with other mods so im not sure it will have anything to do with that

**Comment by CleverNucleus** [comment]
Hi there,
Could you please specify the version of PlayerEx you are using? Additionally, please list the other mods that you have installed.
Thanks.

**Comment by VictorSPM** [comment]
playerex-1.1.8-1.16.5

**Comment by VictorSPM** [comment]
[list.txt](https://github.com/CleverNucleus/PlayerEx/files/8404032/list.txt)

**Comment by VictorSPM** [comment]
but i was getting too dizzy from all the screen shake so i just downloaded the better hurt timer mod to disable the hurt animation and stop the screen shake

**Comment by CleverNucleus** [comment]
Hi there,
This version is no longer supported. However, if I were to hazard a guess as to what is causing your issue, I would suspect BetterHurtTimer.
Thanks.

**Comment by VictorSPM** [comment]
Lol BetterHurtTimer was installed afterwards and also the mod to fix the issue
