### ISSUE TITLE
java.lang.IllegalArgumentException: "playerex:drowning_resistance" is not a valid id in registry

### ISSUE THREAD

**Issue by vhcrack** [CleverNucleus/PlayerEx#62]
[Link to crash log.](https://pastebin.com/raw/f0BwTXyu)
Happens every time I attempt to remove PlayerEx.

**Comment by CleverNucleus** [comment]
Hi there,
 1. The Forge release is no longer supported.
 2. If you are trying to load a world that had previously used PlayerEx, upon removal of the mod that world will no longer be playable as attributes are missing. This is similarly true for many other mods. 

Thanks.
