### ISSUE TITLE
crash fabric create-mc 1.18.2_v0.4.1 +631

### ISSUE THREAD

**Issue by Colddo118** [CleverNucleus/PlayerEx#64]

**Comment by CleverNucleus** [comment]
Hi there,
This is not really a useful issue. Please provide the crash log.
Thanks.

**Comment by CleverNucleus** [comment]
No worries; I'll look into the issue.
Thank you for reporting it.

**Comment by CleverNucleus** [comment]
This behaviour has been found to be caused by Data Attributes - of which a duplicate issue now exists [here](https://github.com/CleverNucleus/Data-Attributes/issues/15). Closing this issue for that reason.
