### ISSUE TITLE
Inventory Tabs Mods Support

### ISSUE THREAD

**Issue by ardissaps** [CleverNucleus/PlayerEx#65]
Cannot press PlayerEx button, it trigger button beneath instead.
![image](https://user-images.githubusercontent.com/82106625/175204943-8af49bfe-fb88-4c21-a8c2-c187e692b190.png)
https://www.curseforge.com/minecraft/mc-mods/inventory-tabs-updated
https://github.com/Andrew6rant/inventorytabs/issues/15

**Comment by CleverNucleus** [comment]
Hi there,
I'll look to add support for Inventory Tabs.
Thanks.

**Comment by Andrew6rant** [comment]
I've fixed the issue on InventoryTabs' side.

![image](https://user-images.githubusercontent.com/57331134/175751413-46d2294c-a06b-4169-b2c4-fbc4567f07ae.png)

The mods are not fully integrated, clicking on any InventoryTab makes the PlayerEx tabs disappear (and vice versa), and both mods have a "home" tab for the player inventory, but there is no longer an overlap.

**Comment by CleverNucleus** [comment]
Hi there @Andrew6rant,
I really appreciate you coming up with a solution so quickly and saving me the time. I realise the mechanism by which I add my tabs is suboptimal at best, so thank you for your patience.

I consider this issue closed now, but if you want to work on further integration and need anything from me, please don't hesitate to ask.

**Comment by ardissaps** [comment]
Oh great I am reinstalling PlayerEx now thank you for you guys!

**Comment by Andrew6rant** [comment]
I haven't released the fix yet, I was planning on dropping the update when I also had EasierCrafting and Scout support. I can push an update now, give me a few minutes

**Comment by Andrew6rant** [comment]
InventoryTabs-0.5.0-1.18.x has been released on CurseForge, Modrinth, and Github, with PlayerEx support and a fix for tabs not being removed when they should be inaccessible.
