### ISSUE TITLE
Refund button in the GUI

### ISSUE THREAD

**Issue by ConqAra** [CleverNucleus/PlayerEx#66]
I know we can refund our attributes through commands, but it would be nice to have an actual refund button in the attributes GUI that refunds your attributes and gives you back all the skill points you've spent. At least make this a config if you don't want this to be to be a default thing.

**Comment by CleverNucleus** [comment]
Hi there,
This is already a feature; PlayerEx has refund buttons available - they only appear when the player has 'refund points' (kind of like skill points). The caveat is that while PlayerEx has this functionality, the only way PlayerEx provides to gain refund points is through a [command](https://github.com/CleverNucleus/PlayerEx/wiki/In-game-Content-1.18.1#commands), or through the API i.e. by creating an addon mod.

[RelicEx](https://www.curseforge.com/minecraft/mc-mods/relicex) is an example of such a mod that provides a way to get refund points in survival - by finding 'Orb of Regret' items. However, it has not been updated past 1.17 and will be a while yet before it updates to 1.18.2.

This is a conscious design choice - I like the commitment that involves having to choose carefully what you skill. I've added the functionality, and even the commands so if someone *really* wants to reset/refund they can, but for it to fit smoothly in survival would require an addon mod.
Thanks.
