### ISSUE TITLE
Max Health Cap

### ISSUE THREAD

**Issue by nateheron** [CleverNucleus/PlayerEx#7]
I think there might be a max health cap at like 1024? Is there a way to either just remove that, or to put an option in the config file where you can put whatever you want as the limit?

**Comment by CleverNucleus** [comment]
Hi there,
Indeed the default cap for max health is 1024. However, on the [PlayerEx mod page](https://www.curseforge.com/minecraft/mc-mods/playerex) the recommended solution is listed:

> **Although AttributeFix is not listed as a dependency, it is recommended! PlayerEx messes with attributes and towards the mid/later stages of the game your attributes will be capped unless you have this installed.**

As per this guidance, I recommend you install [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix) alongside PlayerEx.
Thanks.

**Comment by nateheron** [comment]
Worked perfectly. Great mod btw really love this type of mod and there are only a handful of actually good ones
