### ISSUE TITLE
Minecraft version - 1.18.2, fabric, config file - playerex.jar has no setting as HUD changing.

### ISSUE THREAD

**Issue by MoneySoup008** [CleverNucleus/PlayerEx#74]
The .jar config file shows these following changeable options.
I wanna change the HUD but has nowhere to start it.

{
  "resetOnDeath": false,
  "disableAttributesGui": false,
  "showLevelNameplates": true,
  "skillPointsPerLevelUp": 1,
  "levelFormula": "stairs(x,0.15,2,25,10,22)",
  "levelUpVolume": 100,
  "skillUpVolume": 100,
  "textScaleX": 50,
  "textScaleY": 50,
  "tooltip": "PLAYEREX"
}

**Comment by CleverNucleus** [comment]
The PlayerEx version you are referring to does not implement a HUD.

**Comment by MoneySoup008** [comment]
> The PlayerEx version you are referring to does not implement a HUD.
yeah, but what if I add a code into the file, will it work?

**Comment by CleverNucleus** [comment]
I do not understand what you are asking. You have said "I wanna change the HUD" and showed me the config file options. PlayerEx does not add a HUD. That is why there is no option to disable one in the config. 

Additionally, I do not know what your reply means:

> yeah, but what if I add a code into the file, will it work?

What code? What file? What will or will not work?

I cannot provide help if you do not clearly state what it is you need.
