### ISSUE TITLE
How do I get rid of these?

### ISSUE THREAD

**Issue by KailuKleish** [CleverNucleus/PlayerEx#76]
![unknown](https://user-images.githubusercontent.com/109982612/180838146-63182cde-98e2-435f-8f1c-b3b4c177091a.png)

**Comment by CleverNucleus** [comment]
Hi there,
This is unlikely to be caused by PlayerEx, and more likely to be caused by Eldritch Mobs or similar. Have you tried running the game without PlayerEx and its dependencies to see if you still get this issue?
Thanks.

**Comment by DracoExE** [comment]
> Hi there, This is unlikely to be caused by PlayerEx, and more likely to be caused by Eldritch Mobs or similar. Have you tried running the game without PlayerEx and its dependencies to see if you still get this issue? Thanks.

Can confirm that the mob names and boss bars are part of the Eldritch Mobs mod, not this one (and you can disable them in the mod config)

**Comment by CleverNucleus** [comment]
Excellent.
