### ISSUE TITLE
Snow golems no longer provoke creepers

### ISSUE THREAD

**Issue by PetrichorSPK** [CleverNucleus/PlayerEx#79]
With PlayerEx installed, snow golems still attack creepers, but the snowballs deal no knockback and doesn't provoke the creeper into attacking the golem. Unsure if this is intentional, but if it is, an option to restore vanilla behaviour would be appreciated.

**Comment by PetrichorSPK** [comment]
Tested on 1.18.2

**Comment by CleverNucleus** [comment]
Hi there,
Which version of the mod were you using?

**Comment by PetrichorSPK** [comment]
Tried both 3.2.1 and 3.2.3

**Comment by CleverNucleus** [comment]
Likely a bug, will verify later. 
Thank you for the alert.

**Comment by CleverNucleus** [comment]
This should now be fixed in versions 3.2.4 and 3.3.3. Releases should be available on Modrinth and Curseforge shortly.
Thanks.
