### ISSUE TITLE
Nether portal Bug with forge

### ISSUE THREAD

**Issue by OrionSincoat** [CleverNucleus/PlayerEx#8]
forge-1.16.5-36.1.31

With [HUD] HUD = true

When entering a Nether Portal,
the nether overlay stays opaque and static, it's impossible to see anything.

![image](https://user-images.githubusercontent.com/44932464/123333434-20bb2880-d518-11eb-9121-9c974ae9706b.png)

**Comment by CleverNucleus** [comment]
I'm no longer providing support for the Forge version. Please see the text in bold at the top of [this](https://www.curseforge.com/minecraft/mc-mods/playerex) page. Thanks.
