### ISSUE TITLE
Upgrade limit

### ISSUE THREAD

**Issue by GAM3W** [CleverNucleus/PlayerEx#80]
Hello, I wanted to ask you to help with the function needed for the server. Upgrade limit. At the moment, the mechanics are done very well, but I would like to understand if it is possible to limit any of the stats to a certain amount. 
Version - Forge 1.16.5

**Comment by CleverNucleus** [comment]
Hi there,
This version is no longer supported. However, if I remember correctly attribute limits were hardcoded to ~2B.
Thanks.
