### ISSUE TITLE
[Feature Request] Attribute Reset

### ISSUE THREAD

**Issue by Raeffion** [CleverNucleus/PlayerEx#82]
Love the mod, I'd like the ability to reset any allocated attributes and get skill points back. It doesn't have to be free, I think having it cost either levels or a high value item would be best.

**Comment by CleverNucleus** [comment]
Hi there,
This is not currently something I plan to implement for survival with this mod (there exists a command to do this). However, acknowledging that this is a feature many people desire, there are two items that provide this functionality in the [RelicEx](https://github.com/CleverNucleus/RelicEx) mod, which will hopefully be updated within a week.
Thanks.
