### ISSUE TITLE
[Feature Request] Command to grant Skill Points independent of Level.

### ISSUE THREAD

**Issue by ClockwerkKaiser** [CleverNucleus/PlayerEx#83]
I'd like to humbly request a command which will allow you to skill an input attribute, without having an available skill point.

Something along the lines of:
`/playerex skillup <player> <attribute>`

One use case for this is to combine with a mod like Origins to create unique origin stat bonuses at level 0, such as +2 Con and +1 Dex.

**Comment by CleverNucleus** [comment]
Hi there,
A similar command exists: `/playerex skillAttribute <player> <attribute>`. But it requires the player to have skill points to spend. 

Am I correct in thinking that you want the same command, except that it wouldn't require available skill points? If so, I can compromise slightly and change the aforementioned command to include a boolean argument that determines if the command requires available skill points or not; maybe: `/playerex skillAttribute <player> <attribute> <true|false>`

Would that be acceptable? Please let me know 
Thanks.

**Comment by ClockwerkKaiser** [comment]
That would be perfect!

**Comment by CleverNucleus** [comment]
Output releases for 1.18.2, 1.19 and 1.19.2 with this feature. Available now on Modrinth, pending Curseforge and Github.
