### ISSUE TITLE
[Request] Server-side only support

### ISSUE THREAD

**Issue by elhertz** [CleverNucleus/PlayerEx#86]
Hey! I've been using your mod in my modded server for quite a while and it's been a fantastic experience.
Now my new project is a server with server-side only mods, where vanilla users would join without installing mods on their client (kinda like bukkit/paper but using fabric).

I've seen some devs putting lots of effort into making these kind of mods that don't need to be installed on the client-side and it inspired me to make this new server.
Making this server has been an entertaining challenge so far, but I feel like there's a mod that me and my friends will miss and it is PlayerEx 😥
So I thought... why don't I open an issue and see if they like this idea? so here I am!

_Sorry for the long introduction. I wanted to explain my situation so you understand why would you want this feature._

I've seen devs making server-side ports or adding custom guis to their mods using a resource-pack. Some examples below:
https://modrinth.com/mod/trinkets-polymer/
https://www.curseforge.com/minecraft/mc-mods/biome-technologiestm
https://modrinth.com/mod/polymer-ports-waystones

Libraries used to make these mods:
https://www.curseforge.com/minecraft/mc-mods/polymer
https://github.com/Patbox/sgui

It would be quite an experience to be able to use a mod like PlayerEx on a vanilla client by only using a resourcepack or none at all (_it would look bad without a resourcepack but it would still be usable thanks to sgui_)
Ideally this support could be toggled on the server-side config so PlayerEx or DataAttributes don't ask players to install the mod when you try to join the server.
Players could open the menu by using a command or... take this with a grain of salt cause I'm not a modder but I've read that you can detect when a players click on their inventory slots. The trinkets port is actually using this feature to open their gui when right clicking on an armor slot. PlayerEx could maybe open its gui by right clicking on the recipe book? I don't know if that's really possible but it sounds really exciting.

Well I hope you find this stuff as fascinating as I do myself. I do understand that this could be a lot of work and you may not be interested but I wanted to try and request it nonetheless.
Thank you for the mod. Much love <3!

**Comment by CleverNucleus** [comment]
Hi there,
I'm aware of some of these server-side only mods that function as if they had access to the client, I think they're very cool.

I appreciate your request, but I really have no interest in making the mod server-side only; even if I was I'm about to be very busy. I do think it's possible to make PlayerEx server-side only, as well as its dependency Data Attributes - if anyone wants to make a Polymer port of either I would not mind.

I hope that's okay,
Thanks.

**Comment by elhertz** [comment]
That's fair enough. Thank you for taking the time to make a detailed answer!
