### ISSUE TITLE
Detail Armor Bar Mod

### ISSUE THREAD

**Issue by ardissaps** [CleverNucleus/PlayerEx#87]
I have posted on both side just in case can be worked together with [Detail Armor Bar ](https://modrinth.com/mod/detail-armor-bar)to include armors from bonus stats to the bar. (It is not bug, kind of feature request, no need to be hurry)
https://github.com/RedLime/DetailArmorBar/issues/32
![image](https://user-images.githubusercontent.com/82106625/188150563-c481da12-e41a-487e-bbbc-8efdc5646c86.png)

**Comment by CleverNucleus** [comment]
Hi there,
I have identified the why this happens: Detail Armor Bar doesn't use the raw attribute value ever, just what it thinks *could* be contributing to the armor attribute. Namely, base value, modifiers and what items give what modifiers. 

It is fixable on the end of Detail Armor Bar fairly easily I think; in fact I would be willing to fork and submit a merge request. What version of the mod are you using?
Thanks.

**Comment by ardissaps** [comment]
> Hi there,
> I have identified the why this happens: Detail Armor Bar doesn't use the raw attribute value ever, just what it thinks *could* be contributing to the armor attribute. Namely, base value, modifiers and what items give what modifiers. 
> 
> It is fixable on the end of Detail Armor Bar fairly easily I think; in fact I would be willing to fork and submit a merge request. What version of the mod are you using?
> Thanks.

I see, I am using 1.18.2 fabric detailed armor bar and playerex. Thank you.

**Comment by CleverNucleus** [comment]
Hi there,
I have now submitted a merge request with a fix - it can be viewed [here](https://github.com/RedLime/DetailArmorBar/pull/33).

I am closing this issue now.
Thanks.

**Comment by ardissaps** [comment]
Thank you! :)
