### ISSUE TITLE
[Mod Incompatiability]  Better Combat/Simply Swords

### ISSUE THREAD

**Issue by MLMII** [CleverNucleus/PlayerEx#88]
With Better Combat installed Str doesn't seem to add its damage as expected.

Thank you for your time.

**Comment by CleverNucleus** [comment]
Hi there,
Just to confirm, the mod you are referring to is this [Better Combat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus) mod? Could I get more specific details on this behaviour?

- Is the weapon item tooltip displaying inconsistent numbers (less/more/different from the attributes screen)? 
- Is Strength adding to damage according to the PlayerEx attributes screen and then that is not reflected in the damage being dealt to enemies? Or is it that Strength is not changing the melee damage value?
- Is it _just_ Better Combat and its dependencies with PlayerEx and its dependencies installed? Or a big modpack - in which case, could any other mod be causing this?

Any other specifics would be helpful. It's hard to think of why these two mods would have odd damage interactions, as all Strength is doing is increasing the vanilla damage attribute. Then Better Combat uses the vanilla damage attribute as it wants. There's not even any Mixins here that might be causing micro-incompatibilities.
Thanks.

**Comment by MLMII** [comment]
Sorry, but yeah, its that mod and I am running a pack, I didn't think about the possibility of other mods and I'm sorry for my oversight.  ...  The author at Better Combat tested and wasn't able to reproduce the issue I'm having so its got to be something else, sorry for jumping the gun and wasting your time.


What is happening is that I take a vanilla iron sword, which should be doing 5 damage, for whatever reason it does 4 damage, and when I level up Str either with XP or from RelicEX items I do get the passive health regen, the extra armor, and PlayerEX's combat screen shows my damage value should be increasing but the extra damage just isn't applied.  (Magical trinkets that add to the damage value from other mods do seem to be applied though.)  ...  Oddly enough the damage from critical hits does seem to be added.


Once again thank you and I'm sorry for wasting your time.

**Comment by MLMII** [comment]
Ok, I stumbled upon the answer, I'm an idiot and missed the fact that "Attribute Fix" is incompatible with "Data Attributes" ...  I've just always thrown Attribute Fix into my packs at same time I added other performance fixes from when I was using Forge and never gave it a second thought.


I'm sorry for wasting your time.

**Comment by CleverNucleus** [comment]
No worries at all, I'm glad it all worked out. 👍
