### ISSUE TITLE
Button crashes when using alongside FTB Library

### ISSUE THREAD

**Issue by githubbingitup** [CleverNucleus/PlayerEx#9]
The FTB suite of mods are very important in modpacks and multiplayer servers for anti-grief and creating quests.

If you have FTB Library (which is required for all FTB mods) installed and click the PlayerEX button in the inventory, it crashes the game.

can attach a log if needed.

**Comment by CleverNucleus** [comment]
Hi there,
I'd very much appreciate a log actually. I'll look into this asap.
Thanks for letting me know.

**Comment by githubbingitup** [comment]
Yeah, no prob. Here's one using only the core mods for FTB (Architectfury, cloth-config, fabric API, ftb chunks, ftb library, ftb quests, ftb teams, item filters) and PlayerEx. I've also tested this on older versions of all these mods and had the same issue.

[crash-2021-06-25_15.55.34-client.txt](https://github.com/CleverNucleus/PlayerEx/files/6718537/crash-2021-06-25_15.55.34-client.txt)

**Comment by CleverNucleus** [comment]
Fixed with v2.0.2.

**Comment by githubbingitup** [comment]
wow dude you are fantastic, seriously love your mod and appreciate your awesome work
