### ISSUE TITLE
More config options...

### ISSUE THREAD

**Issue by UsernameNotActive** [CleverNucleus/PlayerEx#91]
Hello. I love this mod, and this ins't really an issue, but I wanted to ask if it was possible to customize the values of the enhancements. For example, reducing the attack speed buff from +0.1 to +0.05.

**Comment by CleverNucleus** [comment]
Hi there,
I'm sorry for the delayed response. It is possible; this can be done using a datapack - please see the [wiki](https://clevernucleus.github.io/playerex-1.18.2_home) for more information on how to do this.
Thanks.
