### ISSUE TITLE
Movement Speed Resets to Minecraft's Default

### ISSUE THREAD

**Issue by Dekonker** [CleverNucleus/PlayerEx#92]
So I was trying to lower the movement speed of the player to 0.05 and add it as a level up mechanic to one of the stats which almost worked. Upon first login to a world the player's movement speed is lowered to the datapack value but if they log out and back in it goes back to Minecraft's default aka 0.1. It also goes to Minecraft's default if you use the reset command. I've been digging around in the code but I can't seem to figure out why this is happening, when it doesn't happen to other attributes. Granted I've only tried changing 3 attributes starting values but both max health and attack speed abide by the entity_types.json value while movement speed does not. 

p.s. After further testing I also noticed that if you die it resets the movement speed attribute back to the entity_types.json value (0.05) ignoring any sort of alteration to the attribute from the levels.

**Comment by Poke097** [comment]
You've managed to get the datapack working? I haven't been able to get the level cap working at all

**Comment by CleverNucleus** [comment]
Hi there,
This is strange behaviour - I will look into it. I appreciate the detailed report.
Thanks.

**Comment by CleverNucleus** [comment]
Fixed with latest release of Data Attributes.
