### ISSUE TITLE
Player Ex causes a blue screen when entering the Abyss Dimension

### ISSUE THREAD

**Issue by DeonHarwnart** [CleverNucleus/PlayerEx#95]
Player Ex causes a blue screen when entering the Abyss Dimension from The Abyss II mod,
I can only see everything in the dimension when using F1 mode
Here is the GitHub that is also related to the issue: https://github.com/Y3Z0N/theabyss/issues/65

I am using 1.16.5

Mod used: The Abyss II and Player Ex

**Comment by CleverNucleus** [comment]
Hi there,
This version of PlayerEx is no longer supported.
Thanks.
