### ISSUE TITLE
Edit Datapack help me<3

### ISSUE THREAD

**Issue by Phillanor** [CleverNucleus/PlayerEx#98]
Hi, I can't change the attributes in the datapack
I tried to install the datapack in different ways, but changing the json files inside (I saved and confirmed the file update in the archive) did not affect the game. I tried to add a basic resistance or a basic attribute value, I did both the re-creation of the world with new attributes, and a reboot.
I can't figure out what I'm doing wrong.
P.s. forge 1.16.5 last version mod

**Comment by CleverNucleus** [comment]
The Forge releases of the mod do not support datapack configuration.
